theme: jekyll-theme-minimal
title: Curso "Introducción a Learning Analytics con ejemplos prácticos"
description: Curso para introducirse en el mundo de Learning Analytics mediante ejemplos prácticos. 
logo: /logo.png
